import { useState, useMemo, useRef, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { ModeToggle } from '@/components/ModeToggle'
import { ArrowLeft, TrendingUp, Wallet, BarChart3, PiggyBank, Building2, Home } from 'lucide-react'
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts'

// ─── Types ────────────────────────────────────────────────────────────────────

type Mode = 'bourse' | 'immo'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatEuro(value: number): string {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value)
}

function formatPercent(value: number, decimals = 2): string {
  return `${value.toFixed(decimals)}%`
}

// ─── Calculations ─────────────────────────────────────────────────────────────

interface BourseDataPoint {
  annee: number
  valeurPortefeuille: number
  totalInvesti: number
  plusValue: number
}

function calculateBourse(
  montantInitial: number,
  versementMensuel: number,
  tauxAnnuel: number,
  dureeAns: number,
): BourseDataPoint[] {
  const tauxMensuel = tauxAnnuel / 100 / 12
  const data: BourseDataPoint[] = []
  let valeur = montantInitial

  for (let annee = 0; annee <= dureeAns; annee++) {
    const totalInvesti = montantInitial + versementMensuel * 12 * annee
    data.push({
      annee,
      valeurPortefeuille: Math.round(valeur),
      totalInvesti: Math.round(totalInvesti),
      plusValue: Math.round(valeur - totalInvesti),
    })
    if (annee < dureeAns) {
      for (let m = 0; m < 12; m++) {
        valeur = valeur * (1 + tauxMensuel) + versementMensuel
      }
    }
  }
  return data
}

interface ImmoDataPoint {
  annee: number
  prixBien: number
  partBanque: number
  patrimoineNet: number
  capitalRembourse: number
  revenusNetCumul: number
}

/**
 * Immo investment simulation.
 *
 * Model:
 * - You buy a property at `prixBien` with `apport` down payment.
 * - The bank lends `prixBien - apport` over `dureeCredit` years at a flat rate
 *   (we use a simplified amortizing loan: constant monthly payment).
 * - Each month the property generates `prixBien * tauxNetMensuel / 100` in net income.
 * - Your "patrimoine net" = equity (capital repaid + apport) + cumulated net income.
 * - The bank's share decreases linearly as capital is repaid.
 * - After the loan is fully repaid, you own 100% of the property value.
 *
 * At 0% yield: after `dureeCredit` years you have only the property price as
 * benefit (since income = 0, equity = full property value, bank share = 0).
 */
function calculateImmo(
  prixBien: number,
  tauxNetAnnuel: number,
  apportPct: number,
  dureeCredit: number,
  dureeAns: number,
): ImmoDataPoint[] {
  const apport = prixBien * apportPct / 100
  const capitalEmprunte = prixBien - apport
  // Monthly net yield (as fraction)
  const tauxNetMensuel = tauxNetAnnuel / 100 / 12

  // Simplified amortization: constant monthly capital repayment (no interest cost modeled
  // since the net yield is already "net" and user controls only the net figure)
  const mensualiteCapital = dureeCredit > 0 ? capitalEmprunte / (dureeCredit * 12) : 0

  const data: ImmoDataPoint[] = []
  let capitalRembourse = 0
  let revenusNetCumul = 0

  for (let annee = 0; annee <= dureeAns; annee++) {
    const partBanque = Math.max(0, capitalEmprunte - capitalRembourse)
    const patrimoineNet = apport + capitalRembourse + revenusNetCumul

    data.push({
      annee,
      prixBien: Math.round(prixBien),
      partBanque: Math.round(partBanque),
      patrimoineNet: Math.round(patrimoineNet),
      capitalRembourse: Math.round(capitalRembourse),
      revenusNetCumul: Math.round(revenusNetCumul),
    })

    if (annee < dureeAns) {
      for (let m = 0; m < 12; m++) {
        // Repay capital (until loan fully repaid)
        const remaining = capitalEmprunte - capitalRembourse
        const repay = Math.min(mensualiteCapital, remaining)
        capitalRembourse += repay

        // Net income generated by the property this month
        revenusNetCumul += prixBien * tauxNetMensuel
      }
    }
  }
  return data
}

// ─── Field ────────────────────────────────────────────────────────────────────

interface FieldProps {
  label: string
  value: number
  onChange: (v: number) => void
  suffix?: string
  step?: number
  min?: number
  hint?: string
}

function Field({ label, value, onChange, suffix, step = 1, min = 0, hint }: FieldProps) {
  const [display, setDisplay] = useState(String(value))
  const lastEmitted = useRef(value)

  useEffect(() => {
    if (value !== lastEmitted.current) {
      lastEmitted.current = value
      setDisplay(String(value))
    }
  }, [value])

  return (
    <div className="space-y-1.5">
      <Label className="text-xs text-muted-foreground">{label}</Label>
      <div className="relative flex items-center">
        <Input
          type="number"
          value={display}
          onChange={e => {
            const raw = e.target.value
            setDisplay(raw)
            const parsed = parseFloat(raw)
            const v = isNaN(parsed) ? 0 : parsed
            lastEmitted.current = v
            onChange(v)
          }}
          step={step}
          min={min}
          className="pr-10 text-sm h-9"
        />
        {suffix && (
          <span className="absolute right-3 text-xs text-muted-foreground pointer-events-none">{suffix}</span>
        )}
      </div>
      {hint && <p className="text-xs text-muted-foreground/60">{hint}</p>}
    </div>
  )
}

// ─── KPI Card ─────────────────────────────────────────────────────────────────

interface KPICardProps {
  title: string
  value: string
  subtitle?: string
  variant?: 'default' | 'positive' | 'warning' | 'negative'
  icon: React.ReactNode
}

function KPICard({ title, value, subtitle, variant = 'default', icon }: KPICardProps) {
  const variantStyles = {
    default: 'border-border/50',
    positive: 'border-emerald-500/30 bg-emerald-500/5',
    warning: 'border-orange-500/30 bg-orange-500/5',
    negative: 'border-red-500/30 bg-red-500/5',
  }
  const valueStyles = {
    default: 'text-foreground',
    positive: 'text-emerald-400',
    warning: 'text-orange-400',
    negative: 'text-red-400',
  }
  return (
    <Card className={`${variantStyles[variant]} transition-all duration-200`}>
      <CardContent className="p-5">
        <div className="flex items-start justify-between mb-3">
          <span className="text-xs text-muted-foreground font-medium uppercase tracking-wide">{title}</span>
          <div className="text-muted-foreground/50">{icon}</div>
        </div>
        <div className={`text-2xl font-bold tabular-nums ${valueStyles[variant]}`}>{value}</div>
        {subtitle && <div className="text-xs text-muted-foreground mt-1">{subtitle}</div>}
      </CardContent>
    </Card>
  )
}

// ─── Main ─────────────────────────────────────────────────────────────────────

export default function InvestissementPage() {
  const [mode, setMode] = useState<Mode>('immo')

  // Bourse params
  const [montantInitial, setMontantInitial] = useState(10000)
  const [versementMensuel, setVersementMensuel] = useState(300)
  const [tauxBourse, setTauxBourse] = useState(7)
  const [dureeBourse, setDureeBourse] = useState(20)

  // Immo params
  const [prixBien, setPrixBien] = useState(200000)
  const [tauxNetAnnuel, setTauxNetAnnuel] = useState(4)
  const [apportPct, setApportPct] = useState(10)
  const [dureeCredit, setDureeCredit] = useState(20)
  const [dureeImmo, setDureeImmo] = useState(20)

  const bourseData = useMemo(
    () => calculateBourse(montantInitial, versementMensuel, tauxBourse, dureeBourse),
    [montantInitial, versementMensuel, tauxBourse, dureeBourse],
  )

  const immoData = useMemo(
    () => calculateImmo(prixBien, tauxNetAnnuel, apportPct, dureeCredit, dureeImmo),
    [prixBien, tauxNetAnnuel, apportPct, dureeCredit, dureeImmo],
  )

  // ── Bourse KPIs
  const bFinal = bourseData[bourseData.length - 1]
  const bPlusValue = bFinal.valeurPortefeuille - bFinal.totalInvesti
  const bRendement = bFinal.totalInvesti > 0 ? ((bFinal.valeurPortefeuille / bFinal.totalInvesti) - 1) * 100 : 0

  // ── Immo KPIs
  const iFinal = immoData[immoData.length - 1]
  const apportEuro = prixBien * apportPct / 100
  const capitalEmprunte = prixBien - apportEuro
  const patrimoineGain = iFinal.patrimoineNet - apportEuro

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border/50 backdrop-blur-sm sticky top-0 z-50 bg-background/80">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link to="/" className="text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <Separator orientation="vertical" className="h-5" />
            <div className="flex items-center gap-2">
              {mode === 'bourse'
                ? <TrendingUp className="w-4 h-4 text-emerald-400" />
                : <Building2 className="w-4 h-4 text-blue-400" />}
              <span className="font-semibold text-sm">Simulateur Investissement</span>
            </div>
          </div>
          <ModeToggle />
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        {/* Mode selector */}
        <div className="flex gap-2 mb-8">
          <button
            onClick={() => setMode('immo')}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-lg border text-sm font-medium transition-all ${
              mode === 'immo'
                ? 'bg-blue-500/10 border-blue-500/50 text-blue-400'
                : 'border-border/50 text-muted-foreground hover:border-border hover:text-foreground'
            }`}
          >
            <Building2 className="w-4 h-4" />
            Immobilier
          </button>
          <button
            onClick={() => setMode('bourse')}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-lg border text-sm font-medium transition-all ${
              mode === 'bourse'
                ? 'bg-emerald-500/10 border-emerald-500/50 text-emerald-400'
                : 'border-border/50 text-muted-foreground hover:border-border hover:text-foreground'
            }`}
          >
            <TrendingUp className="w-4 h-4" />
            Bourse
          </button>
        </div>

        {mode === 'immo' ? (
          <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
            {/* Left: Inputs */}
            <div className="space-y-6">
              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base flex items-center gap-2">
                    <Home className="w-4 h-4 text-blue-400" />
                    Paramètres du bien
                  </CardTitle>
                  <p className="text-xs text-muted-foreground">
                    Le bien appartient en partie à la banque tant que le crédit n'est pas remboursé.
                  </p>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Field
                    label="Prix du bien (€)"
                    value={prixBien}
                    onChange={setPrixBien}
                    suffix="€"
                    step={10000}
                    min={0}
                    hint={`Apport : ${formatEuro(prixBien * apportPct / 100)} — Crédit : ${formatEuro(prixBien * (1 - apportPct / 100))}`}
                  />
                  <Field
                    label="Rendement net annuel (%)"
                    value={tauxNetAnnuel}
                    onChange={setTauxNetAnnuel}
                    suffix="%"
                    step={0.5}
                    min={0}
                    hint="Loyers nets de toutes charges (crédit exclu). À 0 % → aucun revenu, seule l'équité augmente."
                  />
                  <div className="grid grid-cols-2 gap-4">
                    <Field
                      label="Apport (%)"
                      value={apportPct}
                      onChange={setApportPct}
                      suffix="%"
                      step={5}
                      min={0}
                    />
                    <Field
                      label="Durée du crédit (ans)"
                      value={dureeCredit}
                      onChange={setDureeCredit}
                      suffix="ans"
                      step={1}
                      min={1}
                    />
                  </div>
                  <Field
                    label="Horizon de projection (ans)"
                    value={dureeImmo}
                    onChange={setDureeImmo}
                    suffix="ans"
                    step={1}
                    min={1}
                  />
                </CardContent>
              </Card>

              {/* Info card */}
              <Card className="border-blue-500/20 bg-blue-500/5">
                <CardContent className="p-4 space-y-2">
                  <p className="text-xs font-semibold text-blue-400">Comment ça marche ?</p>
                  <ul className="text-xs text-muted-foreground space-y-1 list-disc list-inside">
                    <li>Vous achetez un bien dont <span className="font-medium text-foreground">{formatPercent(100 - apportPct, 0)}</span> appartient à la banque au départ.</li>
                    <li>Chaque mois vous remboursez du capital, réduisant la part de la banque.</li>
                    <li>Le rendement net génère des revenus qui s'accumulent dans votre patrimoine.</li>
                    <li>À <strong>0 %</strong> de rendement, votre bénéfice après <strong>{dureeCredit} ans</strong> = prix du bien (vous avez tout remboursé).</li>
                  </ul>
                </CardContent>
              </Card>
            </div>

            {/* Right: Results */}
            <div className="space-y-6">
              <div>
                <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-4">Indicateurs clés après {dureeImmo} ans</h2>
                <div className="grid grid-cols-2 gap-4">
                  <KPICard
                    title="Patrimoine net"
                    value={formatEuro(iFinal.patrimoineNet)}
                    subtitle="Équité + revenus cumulés"
                    icon={<Wallet className="w-4 h-4" />}
                    variant="positive"
                  />
                  <KPICard
                    title="Part banque restante"
                    value={formatEuro(iFinal.partBanque)}
                    subtitle={iFinal.partBanque === 0 ? 'Crédit remboursé ✓' : `sur ${formatEuro(capitalEmprunte)} emprunté`}
                    icon={<Building2 className="w-4 h-4" />}
                    variant={iFinal.partBanque === 0 ? 'positive' : 'warning'}
                  />
                  <KPICard
                    title="Revenus nets cumulés"
                    value={formatEuro(iFinal.revenusNetCumul)}
                    subtitle={`${formatPercent(tauxNetAnnuel)}/an sur le bien`}
                    icon={<TrendingUp className="w-4 h-4" />}
                    variant={iFinal.revenusNetCumul > 0 ? 'positive' : 'default'}
                  />
                  <KPICard
                    title="Gain vs apport"
                    value={formatEuro(patrimoineGain)}
                    subtitle={`Apport initial : ${formatEuro(apportEuro)}`}
                    icon={<BarChart3 className="w-4 h-4" />}
                    variant={patrimoineGain > 0 ? 'positive' : 'default'}
                  />
                </div>
              </div>

              {/* Chart */}
              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base">Évolution du patrimoine</CardTitle>
                  <p className="text-xs text-muted-foreground">Patrimoine net vs part encore due à la banque</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={250}>
                    <AreaChart data={immoData} margin={{ top: 5, right: 5, left: 0, bottom: 5 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                      <XAxis dataKey="annee" tick={{ fontSize: 11, fill: 'hsl(var(--muted-foreground))' }} tickFormatter={(v) => `${v}a`} />
                      <YAxis tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} width={50} />
                      <Tooltip
                        contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '8px', fontSize: 12 }}
                        formatter={(value: number, name: string) => {
                          const labels: Record<string, string> = {
                            patrimoineNet: 'Patrimoine net',
                            partBanque: 'Part banque',
                            revenusNetCumul: 'Revenus cumulés',
                          }
                          return [formatEuro(value), labels[name] || name]
                        }}
                        labelFormatter={(v) => `Année ${v}`}
                      />
                      <Area type="monotone" dataKey="patrimoineNet" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.15} strokeWidth={2} name="patrimoineNet" />
                      <Area type="monotone" dataKey="partBanque" stroke="#f59e0b" fill="#f59e0b" fillOpacity={0.1} strokeWidth={2} strokeDasharray="4 4" name="partBanque" />
                      {tauxNetAnnuel > 0 && (
                        <Area type="monotone" dataKey="revenusNetCumul" stroke="#10b981" fill="#10b981" fillOpacity={0.08} strokeWidth={1} strokeDasharray="2 2" name="revenusNetCumul" />
                      )}
                    </AreaChart>
                  </ResponsiveContainer>
                  <div className="flex flex-wrap items-center gap-4 mt-2 justify-center">
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <div className="w-4 h-0.5 bg-blue-500 rounded" />
                      Patrimoine net
                    </div>
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <div className="w-4 h-0.5 bg-amber-500 rounded" style={{ borderTop: '2px dashed' }} />
                      Part banque
                    </div>
                    {tauxNetAnnuel > 0 && (
                      <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                        <div className="w-4 h-0.5 bg-emerald-500 rounded" />
                        Revenus cumulés
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Detail table */}
              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base">Détails par année</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-border/50">
                          <th className="text-left text-xs text-muted-foreground font-medium py-2 pr-4">Année</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 px-2">Part banque</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 px-2">Revenus cumulés</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 pl-2">Patrimoine net</th>
                        </tr>
                      </thead>
                      <tbody>
                        {immoData.map(({ annee, partBanque, revenusNetCumul, patrimoineNet }) => (
                          <tr key={annee} className="border-b border-border/30 last:border-0">
                            <td className="py-2 pr-4 text-muted-foreground">{annee}</td>
                            <td className={`py-2 px-2 text-right tabular-nums ${partBanque > 0 ? 'text-amber-400' : 'text-emerald-400'}`}>
                              {formatEuro(partBanque)}
                            </td>
                            <td className="py-2 px-2 text-right tabular-nums text-emerald-400">{formatEuro(revenusNetCumul)}</td>
                            <td className="py-2 pl-2 text-right tabular-nums font-medium">{formatEuro(patrimoineNet)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </CardContent>
              </Card>

              <div className="flex flex-wrap gap-2">
                <Badge variant="outline" className="text-xs">🏠 Prix du bien : {formatEuro(prixBien)}</Badge>
                <Badge variant="outline" className="text-xs">📅 Crédit {dureeCredit} ans</Badge>
                <Badge variant="outline" className="text-xs">📈 Rendement net {formatPercent(tauxNetAnnuel)}/an</Badge>
              </div>
            </div>
          </div>
        ) : (
          /* ── Bourse mode ── */
          <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
            {/* Left: Inputs */}
            <div className="space-y-6">
              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base flex items-center gap-2">
                    <PiggyBank className="w-4 h-4 text-emerald-400" />
                    Paramètres d&apos;investissement
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Field
                    label="Capital initial (€)"
                    value={montantInitial}
                    onChange={setMontantInitial}
                    suffix="€"
                    step={1000}
                    min={0}
                    hint="Montant de départ"
                  />
                  <Field
                    label="Versement mensuel (€)"
                    value={versementMensuel}
                    onChange={setVersementMensuel}
                    suffix="€/mois"
                    step={100}
                    min={0}
                  />
                  <Field
                    label="Rendement annuel (%)"
                    value={tauxBourse}
                    onChange={setTauxBourse}
                    suffix="%"
                    step={0.5}
                    min={-100}
                    hint="Rendement moyen annuel espéré (ex: ETF Monde ~7–8 %)"
                  />
                  <Field
                    label="Durée (ans)"
                    value={dureeBourse}
                    onChange={setDureeBourse}
                    suffix="ans"
                    step={1}
                    min={1}
                  />
                </CardContent>
              </Card>
            </div>

            {/* Right: Results */}
            <div className="space-y-6">
              <div>
                <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-4">Indicateurs clés après {dureeBourse} ans</h2>
                <div className="grid grid-cols-2 gap-4">
                  <KPICard
                    title="Valeur finale"
                    value={formatEuro(bFinal.valeurPortefeuille)}
                    subtitle={`Après ${dureeBourse} ans`}
                    icon={<TrendingUp className="w-4 h-4" />}
                    variant="positive"
                  />
                  <KPICard
                    title="Total investi"
                    value={formatEuro(bFinal.totalInvesti)}
                    subtitle="Capital + versements"
                    icon={<Wallet className="w-4 h-4" />}
                  />
                  <KPICard
                    title="Plus-value"
                    value={formatEuro(bPlusValue)}
                    subtitle="Gains totaux"
                    icon={<BarChart3 className="w-4 h-4" />}
                    variant={bPlusValue > 0 ? 'positive' : bPlusValue === 0 ? 'default' : 'negative'}
                  />
                  <KPICard
                    title="Rendement total"
                    value={formatPercent(bRendement)}
                    subtitle={`Taux : ${formatPercent(tauxBourse)}/an`}
                    icon={<TrendingUp className="w-4 h-4" />}
                    variant={bRendement > 0 ? 'positive' : bRendement === 0 ? 'default' : 'negative'}
                  />
                </div>
              </div>

              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base">Évolution du portefeuille</CardTitle>
                  <p className="text-xs text-muted-foreground">Valeur vs total investi sur {dureeBourse} ans</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={250}>
                    <AreaChart data={bourseData} margin={{ top: 5, right: 5, left: 0, bottom: 5 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                      <XAxis dataKey="annee" tick={{ fontSize: 11, fill: 'hsl(var(--muted-foreground))' }} tickFormatter={(v) => `${v}a`} />
                      <YAxis tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} width={50} />
                      <Tooltip
                        contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '8px', fontSize: 12 }}
                        formatter={(value: number, name: string) => {
                          const labels: Record<string, string> = {
                            valeurPortefeuille: 'Valeur portefeuille',
                            totalInvesti: 'Total investi',
                          }
                          return [formatEuro(value), labels[name] || name]
                        }}
                        labelFormatter={(v) => `Année ${v}`}
                      />
                      <Area type="monotone" dataKey="valeurPortefeuille" stroke="hsl(var(--primary))" fill="hsl(var(--primary))" fillOpacity={0.1} strokeWidth={2} name="valeurPortefeuille" />
                      <Area type="monotone" dataKey="totalInvesti" stroke="hsl(var(--muted-foreground))" fill="hsl(var(--muted-foreground))" fillOpacity={0.05} strokeWidth={2} strokeDasharray="4 4" name="totalInvesti" />
                    </AreaChart>
                  </ResponsiveContainer>
                  <div className="flex items-center gap-4 mt-2 justify-center">
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <div className="w-4 h-0.5 bg-primary rounded" />
                      Valeur portefeuille
                    </div>
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <div className="w-4 h-0.5 bg-muted-foreground rounded" />
                      Total investi
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Detail table */}
              <Card className="border-border/50">
                <CardHeader className="pb-4">
                  <CardTitle className="text-base">Détails par année</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-border/50">
                          <th className="text-left text-xs text-muted-foreground font-medium py-2 pr-4">Année</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 px-2">Investi</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 px-2">Valeur</th>
                          <th className="text-right text-xs text-muted-foreground font-medium py-2 pl-2">+/- Value</th>
                        </tr>
                      </thead>
                      <tbody>
                        {bourseData.map(({ annee, valeurPortefeuille, totalInvesti, plusValue }) => (
                          <tr key={annee} className="border-b border-border/30 last:border-0">
                            <td className="py-2 pr-4 text-muted-foreground">{annee}</td>
                            <td className="py-2 px-2 text-right tabular-nums">{formatEuro(totalInvesti)}</td>
                            <td className="py-2 px-2 text-right tabular-nums font-medium">{formatEuro(valeurPortefeuille)}</td>
                            <td className={`py-2 pl-2 text-right tabular-nums ${plusValue >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                              {plusValue >= 0 ? '+' : ''}{formatEuro(plusValue)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </CardContent>
              </Card>

              <div className="flex flex-wrap gap-2">
                <Badge variant="outline" className="text-xs">📅 Horizon {dureeBourse} an{dureeBourse > 1 ? 's' : ''}</Badge>
                <Badge variant="outline" className="text-xs">📈 Taux {formatPercent(tauxBourse)}/an</Badge>
                <Badge variant="outline" className="text-xs">💰 {formatEuro(versementMensuel)}/mois</Badge>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
